server:
  port: 10143
  ssl:
    enabled: true
    key-store: C:/Users/A1187557/Documents/SSL/keystore.jks
    key-store-password: ENC(bvyUqgivD+D5yK7PskZcKMNV/ufJaTVM)

ldap:
  url: ldaps://<>
  userdn: bindDN name
  password: ENC(UMz3s6vRrb+uMuG2mK3VorfOnmKKvMBVrWoX6e67PwM=)
  userDnPatterns:
    - uid={0},ou=people
dao:
  groupRoleAttribute: cn
  userDnFormat: uid={0},ou=People,dc=bestbuy,dc=com
  groupSearchBase:
    - cn=groupname,ou=Groups

logging:
  level:
    com.maat.bestbuy.integration: trace
    org.springframework: trace

security:
  ignored: /**
  basic:
    enabled: false
spring:
  security:
    enabled: false
management:
  security:
    enabled: false

hystrix:
  command:
    loginCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      metrics:
        rollingStats:
          numBuckets: 10
          timeInMilliseconds: 120000
      circuitBreaker:
        errorThresholdPercentage: 60
        sleepWindowInMilliseconds: 2000
  threadpool:
    loginCommand:
      coreSize: 3

jasypt:
  encryptor:
    password: ${APP_SEC_PASSWD}