spring:
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          isolation: 2
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

server:
  port: 30143
  ssl:
    enabled: true
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWD}

logging:
  level:
    com.maat.bestbuy.integration: trace
    org.springframework: trace
    net.sf.ehcahe: trace

jasypt:
  encryptor:
    password: ${APP_SEC_PASSWD}

hystrix:
  command:
    jobCreateCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      metrics:
        rollingStats:
          numBuckets: 10
          timeInMilliseconds: 120000
      circuitBreaker:
        errorThresholdPercentage: 60
        sleepWindowInMilliseconds: 2000
  threadpool:
    jobCreateCommand:
      coreSize: 3