spring:
  datasource:
    url: <JDBC Connection String>
    username: <DB Username>
    password: ENC(FZWzTltpowrvq5BJR0AJkRpPiJC/pvhsTE5OOt/92z8=)
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          isolation: 2
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

server:
  port: 50143
  ssl:
    enabled: true
    key-store: C:/Users/A1187557/Documents/SSL/keystore.jks
    key-store-password: ENC(bvyUqgivD+D5yK7PskZcKMNV/ufJaTVM)

logging:
  level:
    com.maat.bestbuy.integration: trace
    org.springframework: trace
    net.sf.ehcahe: trace

jasypt:
  encryptor:
    password: ${APP_SEC_PASSWD}

#hystrix:
#  command:
#    getDropdownCommand:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#      metrics:
#        rollingStats:
#          numBuckets: 10
#          timeInMilliseconds: 120000
#      circuitBreaker:
#        errorThresholdPercentage: 60
#        sleepWindowInMilliseconds: 2000
#  threadpool:
#    getDropdownCommand:
#      coreSize: 3


ansible:
  module: python
  path: /ansible/ems/ansible-mw-tube/ExecutePlaybook.py