cloudMessage: hellofromcloud
password: ${password}
routes:
  regionBasedRouting: TTC:100%, TTE:0%
  services:
    -
        name: sm4
        version: v2
        lb: ttc
    -
        name: sm2
        version: v3
        lb: ttc
